openapi: 3.0.1
info:
  title: DANS Vault Catalog API
  description: Catalog service for archives
  version: 1.0.1
servers:
  - url: http://localhost:20100/api
    description: Tape Archive API
paths:
  /tar:
    post:
      tags:
        - tar
      description: Adds a new archive
      operationId: addArchive
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tar'
        required: true
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tar'
  /tar/{id}:
    get:
      tags:
        - tar
      description: Get archive details
      operationId: getArchiveById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tar'
    put:
      tags:
        - tar
      description: Updates an existing archive
      operationId: updateArchive
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tar'
        required: true
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tar'
components:
  schemas:
    Tar:
      required:
        - archival_date
        - tar_parts
        - tar_uuid
        - ocfl_object_versions
        - vault_path
      type: object
      properties:
        tar_uuid:
          type: string
        vault_path:
          type: string
        archival_date:
          type: string
          format: date-time
        tar_parts:
          type: array
          items:
            $ref: '#/components/schemas/TarPart'
        ocfl_objects:
          type: array
          items:
            $ref: '#/components/schemas/OcflObject'
    TarPart:
      type: object
      properties:
        part_name:
          type: string
        checksum_algorithm:
          type: string
        checksum_value:
          type: string
    OcflObject:
      required:
        - bag_id
        - datastation
        - dataverse_pid
        - dataverse_pid_version
        - metadata
        - nbn
        - version_major
        - version_minor
        - object_version
        - ocfl_object_path
        - export_timestamp
      type: object
      properties:
        metadata:
          type: object
        bag_id:
          type: string
        object_version:
          type: string
        datastation:
          type: string
        dataverse_pid:
          type: string
        dataverse_pid_version:
          type: string
        nbn:
          type: string
        version_major:
          type: integer
        version_minor:
          type: integer
        other_id:
          type: string
        other_id_version:
          type: string
        sword_client:
          type: string
        sword_token:
          type: string
        ocfl_object_path:
          type: string
        filepid_to_local_path:
          type: string
        export_timestamp:
          type: string
          format: date-time
